In [130]:
import numpy as np
import scipy as sp
from time import perf_counter as pc
import matplotlib.pyplot as plt

In [60]:
A = np.array([
    [0,3,2],
    [3,5,1],
    [2,1,10]
])

In [115]:
print('np.linalg.eig:')
eigvals, eigvecs = np.linalg.eig(A)
print(eigvals)
print(eigvecs)

np.linalg.eig:
[ 7.44173927 -0.55946271 -2.88227655]
[[-0.48027962 -0.80382519 -0.35099366]
 [-0.62721009  0.59447592 -0.50319567]
 [-0.61313864  0.02152786  0.78968194]]


In [116]:
def eigenvalue(A, v):
    Av = A @ v
    return v @ Av

def powerIteration(A,eps = 10**-9,maxIter=10**5):
    x0 = np.identity(A.shape[0])[0]
    for i in range (maxIter):
        x = x0
        x = A @ x
        x /= np.linalg.norm(x) #nomralizacja
        l = eigenvalue(A,x) #wartość własna
        if(np.linalg.norm(x-x0) < eps):
            return l,x
        x0 = x
    return l,x

powerIteration(A)

(7.441739268043946, array([0.48027962, 0.62721009, 0.61313864]))

In [ ]:
time = []
iteration = []
for i in range(100,501,50):
    print(i)
    A = np.random.randint(-2000,2000,size=(i,i))
    A = (A + A.T)/2
    s = pc()
    powerIteration(A)
    e = pc()
    times.append(e-s)
    iteration.append(i)
    
plt.plot(iteration,time)

100
150
200
250
300
350
400
450
500


In [123]:
N = 100
b = np.random.randint(-2000,2000,size=(N,N))
b_symm = (b + b.T)/2


array([[ -445. ,   964.5,  1381.5, ...,   550.5,   934. ,  -187. ],
       [  964.5,  -866. , -1551. , ...,  -418.5,  -306.5,    15.5],
       [ 1381.5, -1551. , -1373. , ...,   652.5,  -733. ,  -973.5],
       ...,
       [  550.5,  -418.5,   652.5, ...,  1111. ,   219.5,  -120.5],
       [  934. ,  -306.5,  -733. , ...,   219.5,  -353. ,  -328. ],
       [ -187. ,    15.5,  -973.5, ...,  -120.5,  -328. ,  1949. ]])

In [117]:
def inverseIteration(A,eps= 10**-9,maxIter=10**5):
    x0 = np.identity(A.shape[0])[0]
    LU = sp.linalg.lu_factor(A)
    
    for i in range (maxIter):
        x = x0
        x = sp.linalg.lu_solve(LU,x) 
        x /= np.linalg.norm(x)
        if(np.linalg.norm(x-x0) < eps):
            return x
        x0 = x
    return x

inverseIteration(A)

array([ 0.80382519, -0.59447592, -0.02152786])

In [119]:
def rayleigh(A,eps=10**-9,maxIter=10**5):
    I = np.identity(A.shape[0])
    x0 = np.identity(A.shape[0])[0]
   

    for i in range (maxIter):
        x = x0
        lam = np.dot(x,np.dot(A,x))
        
        LU = sp.linalg.lu_factor(A-lam*I)
        x = sp.linalg.lu_solve(LU,x) 
        x /= np.linalg.norm(x)
        
        if(np.linalg.norm(x-x0) < eps):
            return lam,x
        x0 = x
    return lam,x

rayleigh(A)

(-0.5594627131163542, array([ 0.80382519, -0.59447592, -0.02152786]))